using System.Collections.Generic;

namespace RedOwl.Editor
{
    public class AddressableDatabaseGenerator : ICodeGenerator
    {
        public void Generate(string @namespace)
        {
            var namespaces = new HashSet<string>()
            {
                "using System.Collections.Generic;",
                "using RedOwl.Engine;",
                "using UnityEditor;",
                "using UnityEngine;"
            };
            var pairs = new List<string>();
            foreach (var kvp in CodeGenerator.AllAddressables())
            {
                var data = CodeGenerator.GetAssetData(kvp.Key);
                namespaces.Add($@"using {data.Type.Namespace};");
                pairs.Add($@"AddressableDatabase.Add<{data.Type.Name}>(""{kvp.Key}"", new []{{""{string.Join("\", \"", kvp.Value)}""}});");
            }

            string Name = "AddressableDatabaseExtension";
            CodeGenerator.WriteFile(Name, $@"{CodeGenerator.AutoGenerated}
#if UNITY_EDITOR
{CodeGenerator.Join(namespaces, 0)}

namespace {@namespace}
{{
    [InitializeOnLoad]
    public static class {Name}
    {{
        static {Name}()
        {{
            Populate();
        }}

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration)]
        public static void Populate()
        {{
            {CodeGenerator.Join(pairs, 3)}
        }}
    }}
}}
#endif
");
        }
    }
}
