using System.Collections.Generic;
using UnityEditorInternal;

namespace RedOwl.Editor
{
    public class LayersCodeGenerator : ICodeGenerator
    {
        public void Generate(string @namespace)
        {
            var constants = new List<string>();
            var enums = new List<string>();
            int i = 0;
            foreach (string layer in InternalEditorUtility.layers)
            {
                if (string.IsNullOrEmpty(layer)) continue;
                var layerName = layer.Replace(" ", "");
                constants.Add($"public const int {layerName.ToUpper()} = {i};");
                enums.Add($"{layerName} = {i},");
                i++;
            }

            string Name = "Layers";
            CodeGenerator.WriteFile(Name, $@"{CodeGenerator.AutoGenerated}
namespace {@namespace}
{{
    public class UnityLayers
    {{
        {CodeGenerator.Join(constants, 2)}

        public enum Values
        {{
            {CodeGenerator.Join(enums, 3)}
        }}
    }}
}}
");
        }
    }
}