using System;
using RedOwl.Engine;
using Sirenix.Utilities;
using UnityEditor;

namespace RedOwl.Editor
{
    public class ModelGenerator : ICodeGenerator
    {
        public void Generate(string @namespace)
        {
            foreach (var type in TypeCache.GetTypesWithAttribute(typeof(ModelAttribute)))
            {
                var attr = type.GetAttribute<ModelAttribute>();
                string TypeName = type.Name;
                string TypeNamespace = type.Namespace;
                string Title = attr.Title;
                string Tag = attr.Tag;

                CodeGenerator.WriteFile($"{Title}Model", $@"{CodeGenerator.AutoGenerated}
using System;
using RedOwl.Engine;
using UnityEngine;
using {TypeNamespace};

namespace {@namespace}
{{
    [CreateAssetMenu(menuName = ""Red Owl/Models/{Title}"")]
    public class {Title}Model : Model<{TypeName}> {{}}

    [Serializable]
    public class {Title}Reference : ModelReference<{Title}Database, {Title}Model, {TypeName}> {{}}

    public class {Title}Database : Database<{Title}Database, {Title}Model, {TypeName}>
    {{
        protected override string Tag => ""{Tag}"";
    }}
}}
");
            }
        }
    }
}


